### ISSUE TITLE
Pipeline unable to process large documents

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-memory#57]
## Observation
Loading documents greater than a certain size become stuck in pipeline while resulting in the following pipeline failure.

```
Microsoft.SemanticMemory.Pipeline.Queue.AzureQueues.AzureQueue[0]
      Message '598285c6-5d10-40f2-b740-64f763091f45' processing failed with exception, putting message back in the queue
      Azure.RequestFailedException: The request body is too large and exceeds the maximum permissible limit.
RequestId:22cde34c-2003-0047-38e2-e4b1e5000000
Time:2023-09-11T19:05:33.9016314Z
      Status: 413 (The request body is too large and exceeds the maximum permissible limit.)
      ErrorCode: RequestBodyTooLarge

      Additional Information:
      MaxLimit: 65536

      Content:
      ?<?xml version="1.0" encoding="utf-8"?><Error><Code>RequestBodyTooLarge</Code><Message>The request body is too large and exceeds the maximum permissible limit.
RequestId:22cde34c-2003-0047-38e2-e4b1e5000000
Time:2023-09-11T19:05:33.9016314Z</Message><MaxLimit>65536</MaxLimit></Error>

      Headers:
      Server: Windows-Azure-Queue/1.0 Microsoft-HTTPAPI/2.0
      x-ms-request-id: 22cde34c-2003-0047-38e2-e4b1e5000000
      x-ms-version: 2018-11-09
      x-ms-error-code: RequestBodyTooLarge
      Date: Mon, 11 Sep 2023 19:05:33 GMT
      Content-Length: 286
      Content-Type: application/xml

         at Azure.Storage.Queues.MessagesRestClient.EnqueueAsync(QueueMessage queueMessage, Nullable`1 visibilitytimeout, Nullable`1 messageTimeToLive, Nullable`1 timeout, CancellationToken cancellationToken)
         at Azure.Storage.Queues.QueueClient.SendMessageInternal(BinaryData message, Nullable`1 visibilityTimeout, Nullable`1 timeToLive, Boolean async, CancellationToken cancellationToken, String operationName)
         at Azure.Storage.Queues.QueueClient.SendMessageAsync(String messageText, Nullable`1 visibilityTimeout, Nullable`1 timeToLive, CancellationToken cancellationToken)
         at Azure.Storage.Queues.QueueClient.SendMessageAsync(String messageText, CancellationToken cancellationToken)
         at Microsoft.SemanticMemory.Pipeline.Queue.AzureQueues.AzureQueue.EnqueueAsync(String message, CancellationToken cancellationToken) in C:\Users\crickman\source\repos\semantic-memory-sync\dotnet\CoreLib\Pipeline\Queue\AzureQueues\AzureQueue.cs:line 184
         at Microsoft.SemanticMemory.Pipeline.DistributedPipelineOrchestrator.MoveForwardAsync(DataPipeline pipeline, CancellationToken cancellationToken) in C:\Users\crickman\source\repos\semantic-memory-sync\dotnet\CoreLib\Pipeline\DistributedPipelineOrchestrator.cs:line 188
         at Microsoft.SemanticMemory.Pipeline.DistributedPipelineOrchestrator.RunPipelineStepAsync(DataPipeline pipeline, IPipelineStepHandler handler, CancellationToken cancellationToken) in C:\Users\crickman\source\repos\semantic-memory-sync\dotnet\CoreLib\Pipeline\DistributedPipelineOrchestrator.cs:line 156
         at Microsoft.SemanticMemory.Pipeline.DistributedPipelineOrchestrator.<>c__DisplayClass3_0.<<AddHandlerAsync>b__0>d.MoveNext() in C:\Users\crickman\source\repos\semantic-memory-sync\dotnet\CoreLib\Pipeline\DistributedPipelineOrchestrator.cs:line 80
```

## Analysis
The queue message is the entire pipeline state which includes a list of document partitions.  This list can only be so large before it exceeds the maximum allowed queue payload size. (attached doc and pipeline.json)

A scalable design might be to manage state outside of the queue and limit the queue message to a state reference.

- [malala.pipeline.txt](https://github.com/microsoft/semantic-memory/files/12615112/malala.pipeline.txt)

## Source Document
- [I am Malala_ The Story of the Girl Who Stood Up for Education.pdf](https://github.com/microsoft/semantic-memory/files/12615118/I.am.Malala_.The.Story.of.the.Girl.Who.Stood.Up.for.Education.pdf)

**Comment by dluc** [comment]
@crickman https://github.com/microsoft/semantic-memory/pull/66 should fix this issue

**Comment by dluc** [comment]
Thank you for your collaboration and contribution to this issue! As the matter at hand appears to be resolved, I'll be closing this issue for now. However, please don't hesitate to reach out if you have any further questions or concerns. We're more than happy to reopen the issue or continue the conversation as needed.

Wishing you all the best, and happy coding! 😊
