### ISSUE TITLE
Reading document from nested directory cause error while saving memory on disk

### ISSUE THREAD

**Issue by TomaszGrzmilas** [microsoft/semantic-memory#71]
When trying load document from subdirectory, getting error "System.IO.DirectoryNotFoundException":

![image](https://github.com/microsoft/semantic-memory/assets/32311696/994e1603-78ba-4e67-a099-bd3c5a26d0db)

Repo for reproduce:
https://github.com/TomaszGrzmilas/AIAssistant.git

Detail error message:

fail: Microsoft.SemanticMemory.Pipeline.BaseOrchestrator[0]
      Pipeline start failed
      System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Programowanie\AI DEVS\Semantic Kernel\AIAssistant\tmp-memory-files\default\2021.txt\Documents\2021.txt'.
         at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at System.IO.File.Create(String path)
         at Microsoft.SemanticMemory.ContentStorage.DevTools.SimpleFileStorage.WriteStreamAsync(String index, String documentId, String fileName, Stream contentStream, CancellationToken cancellationToken)
         at Microsoft.SemanticMemory.Pipeline.BaseOrchestrator.UploadFormFilesAsync(DataPipeline pipeline, CancellationToken cancellationToken)
         at Microsoft.SemanticMemory.Pipeline.BaseOrchestrator.UploadFilesAsync(DataPipeline currentPipeline, CancellationToken cancellationToken)
         at Microsoft.SemanticMemory.Pipeline.InProcessPipelineOrchestrator.RunPipelineAsync(DataPipeline pipeline, CancellationToken cancellationToken)
         at Microsoft.SemanticMemory.Pipeline.BaseOrchestrator.ImportDocumentAsync(String index, DocumentUploadRequest uploadRequest, CancellationToken cancellationToken)

**Comment by dluc** [comment]
@TomaszGrzmilas the issue should be fixed

**Comment by TomaszGrzmilas** [comment]
@dluc Thank you for solving that one!
